### ISSUE TITLE
running tests on OSX

### ISSUE THREAD

**Issue by samoht** [cryptosense/terminal_size#8]
Any hint on how to run the tests on OSX? I got:

```
# test/mock_ioctl.c:6:10: fatal error: 'asm-generic/ioctls.h' file not found
# #include <asm-generic/ioctls.h>
#          ^
# 1 error generated.
```

**Comment by emillon** [comment]
That was an attempt to import the value of `TIOCGWINSZ` without importing `ioctl` (in order to use an different signature). That's unfortunately not portable.

I just a wrote a fix and pushed it to a `ioctl-varargs` branch, does that work on OSX?

**Comment by samoht** [comment]
That works great, thanks!

**Comment by emillon** [comment]
OK, I'll release a fixed version ASAP. Thanks for the report!
